<?xml version="1.0"?>

<!DOCTYPE config [
<!ELEMENT config (option)+>
<!ELEMENT option (introspect?, map?, alternative*, custom?)>
<!ATTLIST option
  key CDATA #REQUIRED
  static (true|false) 'true'
  priority NMTOKEN '5'
  type (string|boolean|int-options|string-options|string-array|file|path|directory|number|font|class|custom) #REQUIRED
  class CDATA #IMPLIED
  separator CDATA #IMPLIED
>
<!ELEMENT introspect EMPTY>
<!ATTLIST introspect
  class CDATA #REQUIRED
  property CDATA #REQUIRED
>

<!ELEMENT map EMPTY>
<!ATTLIST map
  name CDATA #REQUIRED
>
<!ELEMENT custom EMPTY>
<!ATTLIST custom
  class CDATA #REQUIRED
>
<!ELEMENT alternative (#PCDATA)>
<!ATTLIST alternative
  number NMTOKEN #REQUIRED
>
]>

<config>

  <option key="Bibles.DefaultBible" type="string-options">
    <introspect class="org.crosswire.jsword.book.Defaults" property="BibleByName"/>
    <map name="bible-names"/>
    <!-- set up in OptionsAction.refreshBooks() along with dict and commentary versions -->
  </option>

  <option key="Bibles.DefaultDictionary" type="string-options">
    <introspect class="org.crosswire.jsword.book.Defaults" property="DictionaryByName"/>
    <map name="dictionary-names"/>
  </option>

  <option key="Bibles.DefaultCommentary" type="string-options">
    <introspect class="org.crosswire.jsword.book.Defaults" property="CommentaryByName"/>
    <map name="commentary-names"/>
  </option>

  <option key="Bibles.VersesPerTab" type="number">
    <introspect class="org.crosswire.bibledesktop.display.tab.TabbedBookDataDisplay" property="PageSize"/>
  </option>

  <option key="Sword.ModuleSearchPath" type="path">
    <introspect class="org.crosswire.jsword.book.sword.SwordBookDriver" property="SwordPath"/>
  </option>

  <option key="Sword.DownloadDirectory" type="directory">
    <introspect class="org.crosswire.jsword.book.sword.SwordBookDriver" property="DownloadDir"/>
  </option>

  <option key="Remote.RemoteHost" type="string-array" separator=" ">
    <introspect class="org.crosswire.jsword.book.remote.HttpRemoteBookDriver" property="URLs"/>
  </option>

  <option key="Passages.PersistentNaming" type="boolean">
    <introspect class="org.crosswire.jsword.passage.PassageUtil" property="PersistentNaming"/>
  </option>

  <option key="Passages.BlurringRules" type="int-options">
    <introspect class="org.crosswire.jsword.passage.PassageUtil" property="BlurRestriction"/>
    <alternative number="0"/>
    <alternative number="1"/>
    <alternative number="2"/>
  </option>

  <option key="Passages.BookCase" type="int-options">
    <introspect class="org.crosswire.jsword.passage.BibleInfo" property="Case"/>
    <alternative number="0"/>
    <alternative number="1"/>
    <alternative number="2"/>
    <alternative number="3"/>
  </option>

  <option key="Readings.ReadingsSet" type="string-options">
    <introspect class="org.crosswire.jsword.book.readings.ReadingsBookDriver" property="ReadingsSet"/>
    <map name="readings"/>
  </option>

  <option key="Application.LookAndFeel" type="class">
    <introspect class="org.crosswire.common.swing.LookAndFeelUtil" property="LookAndFeel"/>
  </option>

  <option key="Application.InitialLayout" type="int-options">
    <introspect class="org.crosswire.bibledesktop.desktop.Desktop" property="InitialLayoutType"/>
    <alternative number="0"/>
    <alternative number="1"/>
  </option>

  <option key="BibleDisplay.Converter" type="string-options">
    <introspect class="org.crosswire.jsword.util.ConverterFactory" property="CurrentConverterName"/>
    <map name="converters"/>
  </option>

  <option key="BibleDisplay.ConfigurableStylesheet" type="string-options">
    <introspect class="org.crosswire.bibledesktop.util.ConfigurableSwingConverter" property="ResourceName"/>
    <map name="cswing-styles"/>
  </option>

  <option key="BibleDisplay.ConfigurableFont" type="font">
    <introspect class="org.crosswire.bibledesktop.util.ConfigurableSwingConverter" property="Font"/>
  </option>

  <option key="Advanced.Raw.CacheData" type="boolean">
    <introspect class="org.crosswire.jsword.book.raw.RawBook" property="DefaultCacheData"/>
  </option>

  <option key="Advanced.Reports.ShowErrorsInDialogBox" type="boolean" priority="8">
    <introspect class="org.crosswire.common.swing.ExceptionPane" property="HelpDeskListener"/>
  </option>

  <option key="Advanced.Reports.LogErrorsInLogWindow" type="boolean" priority="8">
    <introspect class="org.crosswire.common.swing.ExceptionShelf" property="HelpDeskListener"/>
  </option>

  <option key="Advanced.SourcePath" type="path" priority="9">
    <introspect class="org.crosswire.common.swing.ExceptionPane" property="SourcePath"/>
  </option>

  <option key="Advanced.XSLT.Cache" type="boolean">
    <introspect class="org.crosswire.common.xml.TransformingSAXEventProvider" property="Cache"/>
  </option>

  <option key="Advanced.Passage.DefaultType" type="int-options">
    <introspect class="org.crosswire.jsword.passage.PassageFactory" property="DefaultPassage"/>
    <alternative number="0"/>
    <alternative number="1"/>
    <alternative number="2"/>
    <alternative number="3"/>
  </option>

  <option key="Advanced.AboutDialog.IncludeAdvancedTabs" type="boolean">
    <introspect class="org.crosswire.bibledesktop.desktop.AboutPane" property="Advanced"/>
  </option>

</config>
